## A brief history

The fishery is managed by the ASFMC and the MAFMC.  There is also a South Atlantic stock that is managed by SAFMC, but we will ignore it.

* BSB was added to the Summer Flounder FMP in 1996 with Amendment 9.  Quarterly quotas for the entire stock were set.
* The MAFMC initially planned for state-level quotas in Amendment 9.  The Regional Director (Administrator) indicated these would not be approved, citing National Standard 7 (minimize costs and avoid unnecessary duplication). The rationale was that NMFS and the state of North Carolina would experience large enforcement and administrative costs. There would be a portion of fishing in NC that was managed by NERO under SF and another that was managed by SERO under Snapper/Grouper.  There was not enough detail about how the NERO quota would be implemented.
* 2001/2002 Amendment 13 did annual quotas and state-by-state allocations to start in 2003/4 and that were managed by ASFMC.
* There were early closures in 1999 (Quarters 2,3,4), 2000 (2,3,4), and 2001 (all).
* Open seasons were getting shorter and shorter; Q3 of 2001 lasted 3 weeks.
* Landings in the North, either because the regulations are looser or because biomass is there.

* 2004 -- Addendum 12 (ASFMC) allowed for transfer of commercial quota across states.  So did Add 19 in 2007.
* Addendum 20 allowed for all kinds of quota to be transferred across states.

* If the coastwide quota is *not* exceeded, state-specific overages are forgiven.
* If the coastwide quota is exceeded, states with underages can contribute them to a pool that is then reallocated.

* 2021 -- Add 31 put in a new formula for commercial quota.  75% of the quota is allocated according to historical fishing. 25% is allocated in proportion to where the biomass is located (based on stock assessment).

There is quite a bit of fishing that occurs within state waters, so the VTR coverage isn't perfect.  It is particularly rough in NY, CT, RI, and MA (especially MA).

The state-level quotas are managed based on the state of landing by ASFMC.  I think this might be introducing some weird incentives in the long-run game between states.


## Relevant current regulations

Three states have IFQ programs (MD, DE, and VA) that started in 2004. I don't know if NC and NJ are valid "untreated" states.  Certainly not for prices.

Maryland [https://www.law.cornell.edu/regulations/maryland/COMAR-08-02-05-21]

* Need a commercial license
* Has up to 14 landing permits, which are issued to people. That person does not need to be aboard the vessel (Operators).
* State quota is allocated to the holders of these permits.
* 50 lb incidental (open access) limits 
* Must be sold to a federally permitted dealer.
* There are restrictions on the type of trawl (4 1/2" cod end, 18" or less roller rig)
* there are restrictions on pot/trap (2 1/2" circular opening, 2" square or 1 3/8 x 5 3/4" rectangular, plus 1 degradable panel or door 3 x 6)
  
Virginia [https://mrc.virginia.gov/Regulations/fr950.shtm]

  * Need a directed bsb permit and either a commercial fisherman license or a seafood landing license.
  * Pots restrictions (same as MD)
  * 40,000 lbs allocated to the "bycatch" fishery and everything else is allocated to the quota fishery
  * Quota allocated based on a person's history from July 1, 1997 to December 31, 2001.
  * Bycatch fishery
  * 200lbs plus the NC legal limit, reduced to 100lbs plus the limit when the bycatch fishery hits 75% or
  * 1,500 lbs as long as that is less than 10% of the weight of SF, scup, longfin squid, and mackerel.
  

Delaware [https://regulations.delaware.gov/AdminCode/title7/3000/3500/3501.shtml]

  * A landing permit is required
  * Up to 6 landing permits for pots (96% of the quota), plus up to 13 hook and line permits (4% of the quota).
  * Firms with a pot permit must have a Federal BSB permit. 
  * One transfer per year
  * I don't see any restrictions on gear or possession, but I see black spaces so these could have been removed.
  * I also don't see anything on the regulations page about initial quota allocations
  * No provision for incidental or bycatch 
  * Pots restrictions (same as MD)


North Carolina

  * These change a bit, but in 2024, the regulations are 
    * Trawls -- 5,000 lb possession limit
    * Pot, Trap, Line -- 3,000 lb of black sea bass.
  * Properly licensed vessel Captains employing trawls can possess landing limits for other states, but it is unlawful to offload those fish in North Carolina

New Jersey

  * There is a complicated set of options, but basically each bi-monthly season has daily trip limit and a number of landings limits.
      * For example: In Jan and Feb 2024, a vessel could choose 4x 750lb trips/week; 2x 1,500lb trips/week, or 1x 3,000 lb trip/week.
  * Vessels can get an "excess of daily limit" license if they are going to hold more than the possession limit and offload in another state.
  * It looks like there is a limited access program
  * There is also a bycatch limit of 10% not to exceed 100 lbs. 
  * 4 1/2" diamond or 4" squarecod end.
  * Any commercial vessel landing black sea bass for sale must sell to a permitted New Jersey Black Sea Bass Dealer.


Rhode Island

  * Limited entry (This is one of the "Unlimited Finfish" endorsements.)  No new licenses, but they can people can enter as others exit. It's probably quite difficult to get a license.
  * https://dem.ri.gov/programs/marine-fisheries/fishamnd.php
  * There some sort of "Aggregate" program for SF and BSB.  Land up to 7x the daily limit, probably 1 x per week?
  * Exemption certificates?
  * Jan 1, the commercial limit was 500lbs/week. Then 750lbs on March1. and 1,500 on April 1. June 9, it was 150lb/day and then July 1 was 50lb/day.
  * Non-resident landing permits -- Available to non-residents only if the landing is charged to the quota of the State in which the vessel making the landing is registered or documented; or, if the State where the vessel making the landing is registered or documented allows Rhode Island residents to land against its quota for that species; or, if the Department pursuant to a fisheries management plan determines there to be excess harvesting capacity in the Rhode Island commercial quota for that species.

Connecticut
  
  * possession limits. winter limits are 2 week periods and then this adjusts during the year
  * Limited access starting at least in 2003.  Zero possession without a Limited Access permit.
  * I didn't see anything about a non-resident landing limit

Massachusetts

  * Limited Entry (not sure when)
  * 12" minimum
  * possession limit of 100lbs between Jan 1 and march 31
  * Lots of complicated regs that start on July 1. Possession limits, Friday/Saturday out that depend on quota usage.
  * Regs are different for Pot and "other gear"
  * I think there might be an owner-operator requirement for pots, which was probably intended for the lobster fishery, but may apply here. I haven't looked too hard.
  * Endorsement transfers 
    * Seller  must have been fished for 2 of the most recent five years.  
    * Buyer must document experience, or be to an immediate family member, or be transferred with accompanying federal permits for fluke and black sea bass.
    * Must involve sale or transfer of fishing-related business assets
  
(https://casetext.com/regulation/code-of-massachusetts-regulations/department-322-cmr-division-of-marine-fisheries/title-322-cmr-700-permits/section-701-form-use-and-contents-of-permits)
and (https://casetext.com/regulation/code-of-massachusetts-regulations/department-322-cmr-division-of-marine-fisheries/title-322-cmr-700-permits/section-706-limited-entry-permits)
  
New York

  * Limited Entry
  * Trip limits that decline as projected landings approach total quota.
  * There is a multi-state possession limit provision. not sure if it's used for bsb or just sf.
  
  
### Takeaways

The "landing restrictions" seem to be doing two things. They are certainly limiting access, but they are also preventing vessels from landing outside their home state.  This is "good" for states that are limited-access with trip-limits. It's probably "bad" for states that are IFQ.  Who is benefitting? Who is not? 

There are two populations managed by the ASFMC. The South stock is from Beaufort/Cape Hatteras, NC north to Hudson Canyon (Statistical Areas 621 and higher, plus statistical areas 614 and 615). The North stock is everything north of that (all the 5XX statistical areas, plus 611,612, 613, 616). 

20-30% of removals come from the commercial fishery, which fishes on slightly smaller individuals than the recreational fishery. 

There were strong year classes in 2011 and 2015.

There in an Inshore movement (beginning of summer) and an offshore movement (late fall). This is an West-East movement, but also a North-South movement.


