

## Summer Flounder

There is a Summer Flounder Management Strategy Evaluation. In addition, S&T has a contractor working on 1 year project to estimate a Summer Flounder production function that contains environmental covariates.  SF and BSB are often caught together, so they are planning to estimate a multi-output production function.

There have been allocation analysis for Scup [@GentnerConsultingGroup2012] and Summer Flounder [@Gentner2010;@Hicks2017; @Hicks2020]. The basic question is all is the optimal allocation between the commercial and recreational sectors. All have some sort of demand model, some model of production, and some valuation coming out of the recreational side.

## Black Sea Bass

The lengths of fish are measured and fed into the stock assessment. These are aggregated to the Area, Gear, Quarter (I think straight to half-year), and Market Category level.  Because there is minimal variation by gear, length samples are combined across gears.  When there are few measured fish in a particular group, lengths are borrowed.

  * Small/Medium/Unclassified -- borrow across regions, then half-year, to preserve size changes due to seasonal growth.
  * Large, Jumbo, and Unclassified - borrow across half-year, then regions to preserve size differences among areas.
  * Then pooled across region/semester combined, year, and region/semester/year
  
I'm really not sure what this means.

Area is based on "area where the fish is caught" (North/South), which is a statistical area thing.  This means that if a dealer buys from boats that fish in two areas, the sizes of those could be different. This is reasonable, but also not. There's probably a transitive property that we could deal with here. 

If PBD is using landings data that is not through CAMS, I'm not sure how I'm going to link back to it.

No length data for unclassified fish from 2020-2023.  The raw data says that this might be as much as 10% of landings, but I think there's some duplicate "unclassified" entries here.


> Another source of uncertainty stemmed from the fact that no length information on individuals in the unclassified market category have been sampled since 2020. Calculating the catch at length for 2021-2023 necessitated borrowing information from before 2020 which introduces additional uncertainty. [BSB management track assessment report]




Miller, A. S., Shepherd, G. R., & Fratantoni, P. S. (2016). Offshore habitatpreference of overwintering juvenile and adult Black Sea Bass, Centropristis striata, and the relationship to year-class success. PLoS One, 11(1), e0147627. https:// doi. org/ 10. 1371/ journ al. pone. 0147627

Morley, J. W., Frölicher, T. L., & Pinsky, M. L. (2020). Characterizing uncertainty in climate impact projections: A case study with seven marine species on the North American Continental Shelf. ICES Journal of Marine Science, 77(6), 2118–2133. https:// doi. org/ 10. 1093/icesj ms/fsaa103

Morley, J. W., Selden, R. L., Latour, R. J., Frölicher, T. L., Seagraves, R. J., & Pinsky, M. L. (2018). Projecting shifts in thermal habitat for 686 species on the North American Continental Shelf. PLoS One, 13(5), e0196127. https:// doi. org/ 10. 1371/ journ al. pone. 0196127

Bandara, R. M. W. J., Curchitser, E., & Pinsky, M. L. (2024). The importance of oxygen for explaining rapid shifts in a marine fish. Global Change Biology, 30, e17008. https://doi.org/10.1111/gcb.17008

https://github.com/wajra/bsb-shift-drivers

https://doi.org/10.5281/zenodo.10023533
