---
title: 'Economic Informed Stock Assessments: Using Prices to Understand the Length of Fish'
author: "Min-Yang Lee"
date: "`r format(Sys.time(), '%B %d, %Y')`" 
documentclass: article
csl: "../ajae_mod.csl"
keywords: "Catch Shares, Quota Prices, Fisheries Economics"
output:
  word_document: null
  pdf_document: 
    includes:
      in_header: "../preamble-latex.tex"
    keep_tex: yes
    pandoc_args: --pdf-engine=pdflatex
    number_sections: true
  html_document: null
fontsize: 12pt
bibliography: "../../library.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

The length- and age-structure of commercial landings is a crucial input to fish stock assessment. In the Northeast United States, NOAA Fisheries deploys samplers to fish dealers to measure the length of commercially landed fish.  Gaps in the data can arise when categories of certain fish simply are not sampled.  When this occurs, the information contained in fish prices can be used to fill in information about the size of these unmeasured fish. The size of individual fish is a characteristic than determines the price of fish; larger specimens nearly always receive higher prices than smaller ones. 

I use the Black Sea Bass fishery in the Northeast United States to illustrate my approach to using economic data to inform stock assessments.  There are 5 prevailing market categories: Jumbo, Large, Medium, Small, and Unclassified.  From 2020 to 2023, 5 to 10% of commercial landings were in the “Unclassified” market category; but no fish in this category were measured. I estimate a hedonic model to confirm that individual size impacts fish prices: “Unclassified” Black Sea Bass are priced between “Large” and “Medium” fish. Then I estimate a multinomial logit that explains market category as a function of prices and other attributes.  I use the results to predict the probability of the “Unclassified” belonging to any of the other market categories, allowing me to construct a price-informed length structure of commercial removals.  
